name: Laravel CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4   # ✅ مهم
          extensions: mongodb
          coverage: xdebug

      - name: Copy .env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Setup SQLite
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run migrations
        run: php artisan  migrate

      - name: Run tests
        run: php artisan test --coverage